# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Lint 
        run: npm run lint

      - name: Test 
        run: npm run test    

      - name: Build 
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        name: community-labeller
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}