name: Snyk Scan
on:
 workflow_dispatch:
 push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: setup snyk
        uses: snyk/actions/setup@master
      - name: snyk monitor
        run: snyk monitor --file=package-lock.json --project-name=${{github.repository}}:package-lock.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_GENERAL_KEY }}
